SELECT * FROM sales_db.sales_data;

-- What is the total revenue and total number of orders
SELECT SUM(orders) AS total_orders, 
SUM(amount) AS total_revenue,
COUNT(*) AS total_txn
FROM sales_data; 

-- What is the Avg order value per transaction
SELECT ROUND(AVG(amount), 2) AS avg_order_value,
ROUND(SUM(amount)/SUM(orders), 2) AS revenue_per_order
FROM sales_data;

-- How many unique customers made purchase
SELECT COUNT(DISTINCT(user_id)) AS unique_customers,
COUNT(DISTINCT(product_category)) AS unique_products
FROM sales_data; 

-- Gender-wise transaction, revenue, avg spend & order 
SELECT gender,
COUNT(*) AS no_of_transaction,
SUM(amount) AS total_revenue,
AVG(amount) AS avg_spend,
SUM(orders) AS total_orders
FROM sales_data
GROUP BY gender; 

-- Age group spending details
SELECT age_group,
COUNT(DISTINCT user_id) AS unique_customers,
COUNT(*) AS no_of_transaction,
SUM(amount) AS total_spend,
ROUND(AVG(amount), 2) AS avg_spend,
SUM(orders) AS total_orders
FROM sales_data
GROUP BY age_group
ORDER BY total_spend DESC; 

-- Top 10 states generates the highest revenues
SELECT state,
SUM(amount) AS total_revenue,
ROUND(AVG(amount), 2) AS avg_spend
FROM sales_data
GROUP BY state
ORDER BY total_revenue DESC;

-- Revenue generated by zone
SELECT zone,
SUM(amount) AS total_revenue,
ROUND(AVG(amount), 2) AS avg_spend
FROM sales_data
GROUP BY zone
ORDER BY total_revenue DESC; 

-- Product category that affect the revenue most 
SELECT product_category,
SUM(amount) AS total_revenue,
ROUND(AVG(amount), 2) AS avg_spend
FROM sales_data
GROUP BY product_category
ORDER BY total_revenue DESC
LIMIT 10; 

-- Which occupation group has the highest purchasing power
SELECT occupation,
COUNT(DISTINCT user_id) AS unique_customer,
SUM(amount) AS purchasing_power,
ROUND(AVG(amount), 2) AS avg_spend_txn
FROM sales_data
GROUP BY occupation
ORDER BY purchasing_power DESC;

-- Marital status effect in spending behaviour
SELECT marital_status, gender,
SUM(amount) AS amt_spend,
ROUND(AVG(amount), 2) AS avg_spend_txn 
FROM sales_data
GROUP BY marital_status, gender; 

-- Revenue contribution(%) by top categories 
SELECT product_category,
ROUND(SUM(amount)*100/(SELECT SUM(amount) 
			 FROM sales_data), 2) AS revenue_percent
FROM sales_data
GROUP BY product_category
ORDER BY revenue_percent DESC
LIMIT 5;

-- Which state has the highest average spend per customer? 
SELECT state,
COUNT(DISTINCT user_id) AS total_customers,
ROUND(SUM(amount)/COUNT(DISTINCT user_id), 2) AS avg_spend
FROM sales_data
GROUP BY state
ORDER BY avg_spend DESC; 

-- Cross-analysis: gender × age group revenue matrix 
SELECT gender, age_group,
SUM(amount) as revenue, 
ROUND(AVG(amount), 2) AS avg_revenue
FROM sales_data
GROUP BY gender, age_group
ORDER BY revenue DESC; 

-- Which product category is most popular by occupation?  
SELECT occupation, product_category, total_orders
FROM (SELECT occupation, product_category,
	  SUM(orders) AS total_orders,
	  ROW_NUMBER() OVER(PARTITION BY occupation ORDER BY SUM(orders) DESC) AS rn
	  FROM sales_data
	  GROUP BY occupation, product_category) ranked
WHERE rn = 1
ORDER BY occupation;

-- Which states are underperforming relative to their zone average? 
WITH zone_stats AS (SELECT state, zone,
					SUM(amount) AS state_revenue, 
					AVG(SUM(amount)) OVER(PARTITION BY zone) AS zone_avg
					FROM sales_data
					GROUP BY state, zone)

SELECT state, zone,
ROUND(zone_avg, 0) AS zone_revenue_avg,
ROUND(state_revenue - zone_avg, 0) AS gap
FROM zone_stats
WHERE state_revenue < zone_avg
ORDER BY gap ASC; 

-- Rank product categories by revenue using dense rank 
WITH cat_rev AS (SELECT product_category,
				 SUM(amount) AS prod_rev,
				 SUM(orders) AS prod_units
				 FROM sales_data
				 GROUP BY product_category) 

SELECT DENSE_RANK() OVER(ORDER BY prod_rev DESC) AS rev_rank,
product_category, prod_rev, prod_units,
ROUND(prod_rev/prod_units, 2) AS rev_per_unit
FROM cat_rev;                 

-- Find the top 3 customers by total spend in each state 
WITH cust_spend AS (SELECT state, user_id, cust_name, 
					SUM(amount) AS total_spend,
                    DENSE_RANK() OVER(PARTITION BY state ORDER BY SUM(amount) DESC) AS rn
					FROM sales_data
					GROUP BY state, user_id, cust_name)

SELECT rn, state, user_id, cust_name
FROM cust_spend
WHERE rn<=3; 

-- Cumulative revenue contribution - which categories form the top 80%? 
WITH cat_rev AS (SELECT product_category,
				 SUM(amount) AS revenue
				 FROM sales_data
				 GROUP BY product_category),
cumulative AS (SELECT product_category, revenue,
               SUM(revenue) OVER (ORDER BY revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total,
			   ROUND(SUM(revenue) OVER (ORDER BY revenue DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) * 100.0 / SUM(revenue) OVER (), 1) AS cumulative_pct
			   FROM cat_rev)

SELECT * FROM cumulative
WHERE cumulative_pct <= 80
ORDER BY revenue DESC;

-- Build a full customer 360 summary per buyer 
SELECT user_id,
MAX(cust_name) AS c_name,
MAX(product_id) AS prod_id,
MAX(age_group) AS c_age_group,
MAX(age) AS c_age,
MAX(marital_status) AS c_marital_status,
COUNT(*) AS num_txn,
SUM(orders) AS total_items_ordered,
SUM(amount) AS total_spend,
ROUND(AVG(amount), 2) AS avg_order_value,
MAX(amount) AS max_spend,
MIN(amount) AS min_spend
FROM sales_data
GROUP BY user_id
ORDER BY total_spend DESC; 